create  database Data_Analysis_Project;
use Data_Analysis_Project;
select * from customer_behaviour_analysis;

-- Business Insights question

-- 1. Which category generates highest revenue?
SELECT
      category,
      round(sum(purchase_amount),2) as highest_revenue
FROM customer_behaviour_analysis
GROUP BY category
ORDER BY Highest_revenue desc;


-- 2 Are discounts actually increasing purchase value

SELECT * FROM customer_behaviour_analysis;
SELECT
     discount_applied,
      ROUND(SUM(purchase_amount),2) as total_revenue,
      ROUND(SUM(purchase_amount),2) as avg_revenue
FROM customer_behaviour_analysis
GROUP BY discount_applied;


/* Business problem:- Discounts may reduce profit without incresing  sales

--🚀 impact:-
			1.identify effectiveness of discounts
            2.Reduce unnessary discount cost
            3. Improve profit margin*/
            
-- 3.What is the total revenue generated by male and female customer

SELECT 
		gender ,
        ROUND(SUM(purchase_amount),2) as highest_revenue
FROM customer_behaviour_analysis
GROUP BY gender
ORDER BY  highest_revenue DESC;


/* ?Business Problem :- Lack of  understanding of revenue contribution by gender segments;
            
  🚀Impact:-
			--Helps design targeted marketing campaigns
            --Improves customer segmention strategy 
            --Enchances personalization efforts */
            
-- 4. which customer used a discount but still spent more then the avarage purchase amount

select
		customer_id,
        purchase_amount,
        discount_applied
from customer_behaviour_analysis
WHERE discount_applied ='yes' AND purchase_amount > (select AVG(purchase_amount) FROM customer_behaviour_analysis)
ORDER BY purchase_amount DESC
LIMIT 10;

-- ? Business proble :-company  cannot identify high_spending customers who are also discount users

     -- 🚀 impact :-
				-- Identifies premium discount _sensitive customers
                -- Enables targeted discount campaigns
				-- Improve customer rotation and revenue

-- 4.Which are the top/bottom 5 products with the highest avarge review rating 
select
     item_purchased ,
     round(avg(review_rating),2) as avg_ratings
from customer_behaviour_analysis
group by item_purchased
order by avg_ratings desc
limit 5;

	select
     item_purchased ,
     round(avg(review_rating),2) as avg_ratings
from customer_behaviour_analysis
group by item_purchased
order by avg_ratings asc
limit 5;

-- Business problem:- No visiblity into product performance based on customer satisfication

      -- 🚀impact:- 
                  -- promotes high performing products
				  -- Improves low_rated products
				  -- Enhances customer experience
-- 5. Avarage Purchase : standard vs Express shipping
select 
	 shipping_type,
     count(distinct customer_id) as order_placed,
     round(avg(purchase_amount),2) as avg_purchase,
     round(sum(purchase_amount),2) as revenue
from customer_behaviour_analysis
-- where shipping_type in ("standard","express")
group by shipping_type
order by revenue desc;
-- Business problem:- unclear if faster shipping leads to higher spending

    -- 🚀impact:-
          -- Helps optimize shipping pricing strategy
          -- Encourage premium shipping adoption
          -- Increase avarage  order value
-- 7.Do Subscribe customer more? compare avarage speed and total revenue between subscribers and non-subscriber

select 
      subscription_status,
      count(customer_id) as users,

      round(avg(purchase_amount),2) as avg_revenue,
      round(sum(purchase_amount),2) as total_revenue
from customer_behaviour_analysis
group by subscription_status;
-- business problem:- The effectiveness of subscriptuon program is unknown
-- 🚀 impact
			-- validates subscription model performance
            -- Improves customer loyality program
            -- Increases  customer lifetime value(clv)
            
-- 8.Top 5 products with highest discount usage
select*from customer_behaviour_analysis;

select 
		item_purchased,
        count(item_purchased)as total_number_of_times_sold,
        count(case when discount_applied='yes' then 1 end) as number_of_times_sold_when_discount_applied,
		count(case when discount_applied='yes' then 1 end)*100.0/count(*) as discount_percent
from customer_behaviour_analysis
group by item_purchased
order by discount_percent limit 5;
-- business problem :- some products may be overly dependent on discount 
              -- 🚀 impact:-
		              -- Identifies discount- driven products
                      -- Helps optimize pricing strategy
                      -- Reduces profit margin loss
-- 9. segment customer into new ,returning and loyal based on their total number of precious purchase ,
-- and show the count of each segment.

select 
	 case 
		when previous_purchases="0" then 'new customer'
        when previous_purchases between 1 and 15 then 'returing_customer'
	else'loyal customers'
    end as customer_segment,
    count(*) as customer_count
    from customer_behaviour_analysis
    group by case 
		when previous_purchases="0" then 'new customer'
        when previous_purchases between 1 and 15 then 'returing_customer'
	else 'loyal customers'
    END;
-- Business Problem:-lack of customer segmentation loads to generic strategies
       -- 🚀 impact:- 
                 -- Enables personalied marketing 
                 -- Improves retention strategies
                 -- Increases conversion rates
								
                                
-- 10. what are the top 3 most purchased products within each category?
with CTE as
(
select 
		category,
        item_purchased,
        count(item_purchased) as most_purchased,
        row_number() over (partition by category order by count(item_purchased) desc) as Rnk
from customer_behaviour_analysis
group by category,item_purchased
)
select * from CTE 
where RNk<=3;
-- Business Problem:- The company doesn't know top-performing products within categories

-- 🚀Impact
				-- Improves product placement & recommendation
				-- Helpds inventory optimization
				-- Increases sales through best sellers
-- 11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?

 

SELECT
	CASE 
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
		ELSE 'Normal Buyers'
	END AS customer_type,
	subscription_status,
	COUNT(*) AS customer_count,
	COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY CASE 
										WHEN previous_purchases > 5 THEN 'Repeat Buyers'
										ELSE 'Normal Buyers'
									END
									) AS percents

FROM customer_behaviour_analysis
GROUP BY CASE 
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
		ELSE 'Normal Buyers'
	END,subscription_status;
-- 1047

-- ❓ Business Problem :- Unclear relationship between loyalty and subscription.

-- 🚀 Impact:- 
			-- Improves subscription targeting
			-- Increases conversion to paid programs
			-- increase customer retention strategy

----------------------------------------------------------------------------------------------------------------------------

-- 12. What is the revenue contribution of each age group ? 



SELECT 
	CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN Age BETWEEN 26 AND 35 THEN '26-35'
		WHEN Age BETWEEN 36 AND 50 THEN '35-50'
		ELSE '51+'
	END AS age_group,
	ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_behaviour_analysis
GROUP BY CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN Age BETWEEN 26 AND 35 THEN '26-35'
		WHEN Age BETWEEN 36 AND 50 THEN '35-50'
		ELSE '51+'
	END
	ORDER BY total_revenue DESC

-- ❓ Business Problem:- No visibility into which age group contributes most to revenue.

-- 🚀 Impact:-
			--  Enables age-based targeting
			-- Enhances 		

        

